### ISSUE TITLE
confluence_searcher

### ISSUE THREAD

**Issue by ghost** [laconicwolf/random-python#1]
The command 'python3 confluence_searcher.py -h' does not work as well as for '--help'

Also, this does not work for those confluences that have a logon.

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
The error for -h --help

Traceback (most recent call last):
  File "confluence_searcher.py", line 255, in <module>
    args = parser.parse_args()
  File "/usr/lib/python3.6/argparse.py", line 1743, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.6/argparse.py", line 1775, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.6/argparse.py", line 1981, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.6/argparse.py", line 1921, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.6/argparse.py", line 1849, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.6/argparse.py", line 1033, in __call__
    parser.print_help()
  File "/usr/lib/python3.6/argparse.py", line 2375, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib/python3.6/argparse.py", line 2359, in format_help
    return formatter.format_help()
  File "/usr/lib/python3.6/argparse.py", line 291, in format_help
    help = self._root_section.format_help()
  File "/usr/lib/python3.6/argparse.py", line 222, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.6/argparse.py", line 222, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.6/argparse.py", line 222, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.6/argparse.py", line 222, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.6/argparse.py", line 532, in _format_action
    help_text = self._expand_help(action)
  File "/usr/lib/python3.6/argparse.py", line 619, in _expand_help
    return self._get_help_string(action) % params
TypeError: unsupported operand type(s) for %: 'tuple' and 'dict'

**Comment by ghost** [comment]
It does work for those confluence without logins.

**Comment by laconicwolf** [comment]
Fixed. The problem is how argparse handles me breaking up a string by using a tuple in the help options. Like in:
```python
help=("This string is too long so I will ",
      "put it on another line.")
```

Removing the tuple fixed the problem. Strange that I haven't noticed or run into that before.

Thanks!
